network: 'testnet'
metaChainShardId: 4294967295
api:
  public: true
  private: true
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 100
  cacheWarmer: true
urls:
  api:
    - 'https://testnet-api.elrond.com'
    - 'https://devnet-api.elrond.com'
    - 'https://api.elrond.com'
  elastic:
    - 'https://testnet-index.elrond.com'
  gateway:
    - 'https://testnet-gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://delegation.maiarbrowser.com/providers'
  media: 'https://testnet-media.elrond.com'
  nftThumbnails: 'https://testnet-media.elrond.com/nfts/thumbnail'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqp699jngundfqw07d8jzkepucvpzush6k3wvqyc44rx'
  delegationShardId: 2
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
security:
  admins:
  jwtSecret: