network: 'mainnet'
metaChainShardId: 4294967295
useLegacyElastic: true
api:
  public: true
  private: true
cron:
  transactionProcessor: true
  transactionProcessorMaxLookBehind: 1000
  cacheWarmer: true
urls:
  api:
    - 'https://api.elrond.com'
    - 'https://devnet-api.elrond.com'
    - 'https://testnet-api.elrond.com'
  elastic:
    - 'https://index.elrond.com'
  gateway:
    - 'https://gateway.elrond.com'
  redis: '127.0.0.1'
  providers: 'https://internal-delegation-api.elrond.com/providers'
  media: 'https://media.elrond.com'
  nftThumbnails: 'https://media.elrond.com/nfts/thumbnail'
caching:
  cacheTtl: 6
  processTtl: 600
  poolLimit: 10
keepAliveTimeout:
  downstream: 61000
  upstream: 60000
contracts:
  esdt: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqzllls8a5w6u'
  auction: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqplllst77y4l'
  staking: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqllls0lczs7'
  delegationManager: 'erd1qqqqqqqqqqqqqqqpqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqylllslmq6y6'
  delegation: 'erd1qqqqqqqqqqqqqpgqxwakt2g7u9atsnr03gqcgmhcv38pt7mkd94q6shuwt'
  delegationShardId: 2
inflation:
  - 1952123
  - 1746637
  - 1541150
  - 1335663
  - 1130177
  - 924690
  - 719203
security:
  admins:
  jwtSecret: